version: '3'

services:
  flask-api:
    container_name: flask-api
    build:
      context: ./inventory-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-db:5432/postgres

  postgres-db:
    image: postgres:13.1-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
# volumes:
#   postgres-data:  
