version: '3.0'
services:
  flask-api:
    image: flask-api:1.0
    container_name: flask-api
    build:
      context: ./inventory-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-db:5432/postgres

  postgres-db:
    image: postgres:13.1-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ui:
    image: ui:1.0  
    container_name: ui
    build:
      context: ./ui  # Path to your UI directory containing Dockerfile and static files
      dockerfile: Dockerfile  # Assuming you have a Dockerfile in the ./ui directory
    ports:
      - "8080:80"  # Expose UI on port 8080
    depends_on:
      - flask-api  # Optional: UI might depend on the API being available

# Uncomment if you need persistent storage for PostgreSQL
volumes:
  postgres-data:
