apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - image: 1047473086961/ui:1.0
        imagePullPolicy: IfNotPresent
        name: ui
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
