apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ui
  name: ui
spec:
  type: NodePort
  ports:
  - protocol: TCP
    NodePort: 30002
    port: 8091
    targetPort: 80
  selector:
    io.kompose.service: ui